name: 'Pull request: Run unit test'

on:
  pull_request:
    branches:
      - dev
      - master
env:
  SPRING_PROFILES_ACTIVE: ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Test
        run: ./mvnw test